name: Publish Pkg

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Build & Publish package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Test
        run: npm test